# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=70)),
                ('emotion', models.IntegerField(default=999999999999)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('socialbility', models.FloatField(default=123456789.0)),
                ('recent_emotion', models.IntegerField(default=123456789)),
                ('personality', models.CharField(max_length=9999)),
                ('impact', models.CharField(max_length=9999)),
                ('closeness', models.CharField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.CharField(max_length=50)),
                ('frame_id', models.IntegerField(default=123456789)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Story'),
        ),
        migrations.AddField(
            model_name='characterobjects',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Story'),
        ),
        migrations.AddField(
            model_name='character',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Frame'),
        ),
    ]
