# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_characterobjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='position',
        ),
        migrations.RemoveField(
            model_name='characterobjects',
            name='initial_emotion',
        ),
        migrations.AddField(
            model_name='character',
            name='emotion',
            field=models.IntegerField(default=999999999999),
        ),
        migrations.AddField(
            model_name='characterobjects',
            name='recent_emotion',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_id',
            field=models.IntegerField(default=123456789),
        ),
        migrations.AlterField(
            model_name='characterobjects',
            name='socialbility',
            field=models.FloatField(default=123456789.0),
        ),
    ]
